[versions]
kotlin = "1.9.25"
kotlinxCoroutines = "1.9.0"
ktlint = "12.1.2"
kotlinLogging = "3.0.4"
springBoot = "3.4.0"
springDependencyManagement = "1.1.6"
springCloud = "2024.0.0"
jib = "3.4.4"
querydsl = "5.1.0"
