[versions]
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
ktlint = "13.1.0"
kotlinLogging = "7.0.13"
springBoot = "3.5.7"
springDependencyManagement = "1.1.7"
springCloud = "2025.0.0"
jib = "3.4.5"
querydsl = "7.0"
